package rpgram.core;

import rpgram.core.utils.Random;

@SuppressWarnings("SpellCheckingInspection")
public class NamesGenerator {
    public static String getRandomVillageName() {
        return villageNames[Random.randInt(0, NamesGenerator.villageNames.length - 1)];
    }

    public static String getRandomNpcName() {
        return npcNames[Random.randInt(0, NamesGenerator.npcNames.length - 1)];
    }

    private static final String[] villageNames = {
        "Robinson",
        "Kahoka",
        "Boothwyn",
        "Gresham",
        "East Hodge",
        "Hortonville",
        "Ranchester",
        "Weekapaug",
        "Port Henry",
        "Summerville",
        "South Monrovia Island",
        "Union Deposit",
        "St. Augustine South",
        "Lumberport",
        "Utuado",
        "South Shore",
        "Meadow",
        "Tubac",
        "Seabrook Farms",
        "Edgard",
        "Frytown",
        "Cold Spring",
        "Brewster",
        "Hillandale",
        "Ten Broeck",
        "Beeville",
        "World Golf Village",
        "Gallipolis",
        "Glasford",
        "Plain",
        "Harrell",
        "Arbon Valley",
        "Wilson City",
        "Yulee",
        "Carlyle",
        "Start",
        "Tavistock",
        "Buffalo Center",
        "James Town",
        "Murphy",
        "Speedway",
        "Octa",
        "Fayette City",
        "Bear Grass",
        "Latrobe",
        "Penn Estates",
        "East Massapequa",
        "Minidoka",
        "Glenside",
        "Newsoms"
    };

    private static final String[] npcNames = {
        "Robert",
        "Adfrith",
        "Earorht",
        "Berteph Hopyc",
        "Atwith",
        "Gyles Mery",
        "Frica",
        "Bearda",
        "Wearda",
        "Ralphye",
        "Rewis",
        "Waldu",
        "Pholes",
        "Oswulf",
        "Adsic",
        "Rewyn",
        "Balda",
        "Erelm",
        "Tane",
        "Ealdrehrt",
        "Wealda",
        "Narder",
        "Eadric",
        "Phamund Rowley",
        "Gery",
        "Atwund",
        "Cuthhelm",
        "Here",
        "Wini",
        "Thony Willey",
        "Wine",
        "Lafa",
        "Anstard",
        "Reder",
        "Rewilh",
        "Phileon Quinte",
        "Artis Chammyth",
        "Breyny",
        "Anthol",
        "Here",
        "Lesym",
        "Helmund",
        "Jamond",
        "Freder Cote",
        "Symund Aner",
        "Droguy",
        "Robert",
        "Stephye",
        "Hearda",
        "Rarder",
        "Philonikos Grelot",
        "Cyriack Verlet",
        "Thim Géza",
        "Dob Iturburu",
        "Ingelramnus Gersek",
        "Oxel Demertzis",
        "Kreon Tappen",
        "Lydus de Caro",
        "Theodoric Andrássy",
        "Daphis d'Angers",
        "Godafre Merklein",
        "Palladius Gereke",
        "Caspar Durville",
        "Astigar Schettina",
        "Tinnelt Gallieni",
        "Onias Meessens",
        "Anaxagoras Poignant",
        "Clonius Jarre",
        "Sosibios Joubert",
        "Geleon Lobato",
        "Emmeran Barrutia",
        "Porphyrios Dautzenburg",
        "Hadubrand la Bruiere",
        "Grifo Latreille",
        "Aldus Maloros",
        "Aeschreas Huyler",
        "Bladi Scala",
        "Anthonius Singer",
        "Inguma Chocholi",
        "Oswyn Scheffler",
        "Ricimer Gan",
        "Vincey Pipinelis",
        "Ganelon Geldmeyer",
        "Tybout Pongratz",
        "Phorbas Boomer",
        "Heudebrand Quincarnon",
        "Yvain Ruspoli",
        "Godfrey Forget",
        "Philpot Bajraktari",
        "Urdaspal Weiglein",
        "Metrophanes le Vicomte",
        "Reinfred Heideck",
        "Tlepolemus Sirakov",
        "Theodore Pappou",
        "Lovet Andreucci",
        "Urtungo Stenneke",
        "Othuel Raab",
        "Michaelius Malisse",
        "Borchert Crapanzano",
        "Beuve Ludendorff"
    };
}
